In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

In [34]:
data = pd.read_excel("Boston Housing Dataset 1978.xlsx")
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)

In [35]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [36]:
data.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [37]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000
mean,1.420825,12.721239,10.304889,0.077434,0.540816,6.343538,65.557965,4.043570,7.823009,377.442478,18.247124,369.826504,11.441881,23.750442
std,2.495894,24.326032,6.797103,0.267574,0.113816,0.666808,28.127025,2.090492,7.543494,151.327573,2.200064,68.554439,6.156437,8.808602
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,6.300000
25%,0.069875,0.000000,4.930000,0.000000,0.447000,5.926750,40.950000,2.354750,4.000000,276.750000,16.800000,377.717500,6.587500,18.500000
50%,0.191030,0.000000,8.140000,0.000000,0.519000,6.229000,71.800000,3.550400,5.000000,307.000000,18.600000,392.080000,10.250000,21.950000
75%,1.211460,20.000000,18.100000,0.000000,0.605000,6.635000,91.625000,5.401100,7.000000,411.000000,20.200000,396.157500,15.105000,26.600000
max,9.966540,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,34.410000,50.000000

In [38]:
x = data.drop(columns=["MEDV"])
y = data["MEDV"]

In [39]:
indices_train = np.random.choice(data.index, size=int(0.5 * len(data)), replace=False)
indices_test = data.index.difference(indices_train)
data_train = data.loc[indices_train]
data_test = data.loc[indices_test]

In [40]:
x_train = data_train.drop(columns=["MEDV"])
y_train = data_train["MEDV"]

x_test = data_test.drop(columns=["MEDV"])
y_test = data_test["MEDV"]

In [52]:
scaler = StandardScaler().fit(x_train)
x_scaled = scaler.transform(x_train)

In [53]:
ols = sm.OLS(y_train, sm.add_constant(x_scaled))
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.835
Model:                            OLS   Adj. R-squared:                  0.825
Method:                 Least Squares   F-statistic:                     82.40
Date:                Thu, 04 Sep 2025   Prob (F-statistic):           2.74e-75
Time:                        17:08:12   Log-Likelihood:                -606.61
No. Observations:                 226   AIC:                             1241.
Df Residuals:                     212   BIC:                             1289.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         23.4903      0.243     96.516      0.000      23.011      23.970
x1            -1.9105      0.663     -2.883      0.004      -3.217      -0.604
x2             0.4051      0.381      1.063      0.289      -0.346       1.156
x3             0.2689      0.454      0.592      0.555      -0.627       1.165
x4             0.7894      0.256      3.089      0.002       0.286       1.293
x5            -0.8557      0.515     -1.663      0.098      -1.870       0.159
x6             5.5383      0.383     14.464      0.000       4.784       6.293
x7            -1.4647      0.453     -3.236      0.001      -2.357      -0.572
x8            -2.0934      0.478     -4.384      0.000      -3.035      -1.152
x9             2.0626      0.748      2.757      0.006       0.588       3.537
x10           -1.2099      0.633     -1.911      0.057      -2.458       0.038
x11           -1.6323      0.326     -5.002      0.000      -2.275      -0.989
x12            0.6091      0.269      2.265      0.025       0.079       1.139
x13           -0.5959      0.451     -1.323      0.187      -1.484       0.292
==============================================================================
Omnibus:                       82.458   Durbin-Watson:                   1.883
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              437.265
Skew:                           1.327   Prob(JB):                     1.12e-95
Kurtosis:                       9.276   Cond. No.                         9.86
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [60]:
x_test_scaled = scaler.transform(x_test)
y_pred = results.predict(sm.add_constant(x_test_scaled))
r2 = r2_score(y_test, y_pred)
r2

0.541585061479511

In [69]:
lr = LinearRegression()
lr.fit(x_scaled, y_train)
y_pred_lr = lr.predict(x_test_scaled)
r2_lr = r2_score(y_test, y_pred_lr)  
r2_lr

0.5415850614795112

In [68]:
lr_test = LinearRegression()
lr_test.fit(x_test_scaled,y_test)
y_pred_test = lr_test.predict(x_test_scaled)
r2_test = r2_score(y_test, y_pred_test)
r2_test

0.7140867713749308